### ISSUE TITLE
Argument Null Exception from JSON.NET on initialising

### ISSUE THREAD

**Issue by trymnilsen** [solr-express/solr-express#237]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Using a slimmed down version of the SimpleUse.NetCore sample I get a

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value

   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at SolrExpress.Builder.ExpressionBuilder`1.<>c.<LoadSolrSchemaFields>b__6_1(JToken v) in /Users/trymnilsen/code/.../solr-express/src/SolrExpress/Builder/ExpressionBuilder.cs:line 42
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at SolrExpress.Builder.ExpressionBuilder`1.LoadSolrSchemaFields() in /Users/trymnilsen/code/.../solr-express/src/SolrExpress/Builder/ExpressionBuilder.cs:line 39
   at SolrExpress.Builder.ExpressionBuilder`1.LoadDocument() in /Users/trymnilsen/code/..../solr-express/src/SolrExpress/Builder/ExpressionBuilder.cs:line 166
   at SolrExpress.Utility.CoreDependecyInjection.Configure[TDocument](ISolrExpressServiceProvider`1 serviceProvider, SolrExpressOptions options) in /Users/trymnilsen/code/..../solr-express/src/SolrExpress/Utility/CoreDependecyInjection.cs:line 30
   at SolrExpress.DI.CoreClr.IServiceCollectionExtension.AddSolrExpress[TDocument](IServiceCollection serviceCollection, Action`1 builder) in /Users/trymnilsen/code/.../solr-express/src/SolrExpress.DI.CoreClr/IServiceCollectionExtension.cs:line 29
   at SimpleUse.NetCore.Program.Main(String[] args) in /Users/trymnilsen/code/.../solr-express/sample/SimpleUse.NetCore/Program.cs:line 16
```

Exception from adding configuring/Initializing Solr.

## Expected behavior
No exception and fetching all `TechProduct` document

## Minimal reproduction of the problem with instructions

Change a field in TechProduct.cs to work around https://github.com/solr-express/solr-express/issues/235

In my case `TechProduct.cs` looks like this now 

```
using SolrExpress;
using System;

namespace SimpleUse.NetCore
{
    public class TechProduct : Document
    {
        [SolrField("name")]
        public string Name { get; set; }

        [SolrField("manu")]
        public new string Id { get; set; }
    }
}
```

And a minor change to `Program.cs`
```
            techProducts
                .Select()
                .QueryAll()
                .Execute()
                .Document(out var documents);
```

The offending lines of code where the exception is thrown is identitcal to the sample (apart for the solr URL)

```
            var services = new ServiceCollection()
                .AddSolrExpress<TechProduct>(builder => builder
                    .UseHostAddress("http://localhost:32768/solr/techproducts")
                    .UseSolr5());
```

## Environment

- Connect to a SOLR version: 6.6.0
- Connect to a SOLR in cloud mode? [ ] Yes [x] No
- I'm coding using platform:  Mac
- Using .net version: netcoreapp2.0 
- Using SolrExpress package:  SolrExpress.Solr5
- Using SolrExpress package version: 5.1.1
- Using SolrExpress.DI package:  Native .Net Core
- Using SolrExpress.DI package version: 5.1.1

**Comment by trymnilsen** [comment]
Seems to be an issue if the Solr Schema does not contain a `indexed` or `stored` field.
Perhaps `LoadSolrSchemaFields()` in `ExpressionBuilder.cs` can be changed to account for this? If not I think it should throw a more understandable exception if solr-express are not going to implicitly assume schema field values.

I fixed it by adding null checks to fetching the values from the response JSON.
```
            this.FieldSchemas = allFields["fields"]
                .ToDictionary(
                    k => k["name"].Value<string>(),
                    v => new FieldSchema
                    {
                        FieldName = v["name"].Value<string>(),
                        //Default values for index and stored retrieved from 
                        //https://lucene.apache.org/solr/guide/6_6/field-type-definitions-and-properties.html#field-default-properties
                        IsIndexed = v["indexed"] != null ? v["indexed"].Value<bool>() : true,
                        IsStored = v["stored"] != null ? v["indexed"].Value<bool>() : true
                    });
``` 
Would you like a PR for it?

**Comment by diegobrum** [comment]
Sure! But I need check more this bug, because I think this is occurs only when using Solr6

**Comment by diegobrum** [comment]
@trymnilsen , please see v5.1.2
