### ISSUE TITLE
Unable to add two fq filter query expressions (usecase: two {!join } filters)

### ISSUE THREAD

**Issue by camelinckx** [solr-express/solr-express#263]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

We are unable to add multiple fq (filter query) local parameters
We need this in order to add two {!join} which join other solr cores for filtering
On Execute the following exception is raised:
```
System.ArgumentException
  HResult=0x80070057
  Message=Can not add property fq to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at SolrExpress.Solr5.Search.Parameter.LocalParameter`1.AddResultInContainer(JObject container)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SolrExpress.Solr5.Search.SearchItemCollection`1.Execute(String requestHandler)
   at SolrExpress.Search.DocumentSearch`1.Execute()

```

## Expected behavior

The multiple fq local parameters would be added to the Uri and the Solr select query would succeed

## Minimal reproduction of the problem with instructions

1. Add two fq local parameters
2. Execute the search

## Environment

- Connect to a SOLR version: 6.5.1
- Connect to a SOLR in cloud mode? [ ] Yes [X] No
- I'm coding using platform:  Windows
- Using .net version:  netcoreapp2.1
- Using SolrExpress package: 
- Using SolrExpress package version: 5.3.1
- Using SolrExpress.DI package: Native .Net Core
- Using SolrExpress.DI package version: 5.3.1

## Other

On the solr query UI, there is a (+) button next to the fq parameter that can allow you to enter an additional fq parameter. You can also reproduce a successful test using that.

**Comment by diegobrum** [comment]
Hi @camelinckx 

See below example

``` csharp
techProducts
    .Select()
    .Filter(q => q.InStock, true)
    .Filter(q => q.Popularity, query => query.GreaterThan(5))
```
